config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :contacts

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    get "view", to: "pages#view"
    resources :tickets, only: [:new, :create,:index, :show, :edit, :update]  do
      collection do
        get :show_ticket
      end
    end
    resources :messages, only: [:new, :create, :index] do
      collection do
        delete :clear
      end
    end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.


  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/home.html.erb
<div class="container">
<div class="count m-4 d-flex gap-3">
  <div class="ticket-count-box flex-fill">
    <p>Open Tickets</p>
    <h4><%= @open_tickets_count %></h4>
  </div>
  <div class="ticket-count-box flex-fill">
    <p>Closed Tickets</p>
    <h4><%= @closed_tickets_count %></h4>
  </div>
</div>

<h1>Ticket Status Overview</h1>

<div class="d-flex gap-4 mt-4" >
  <div class="col-md-6 chart-box">
    <%= pie_chart Ticket.where.not(status: nil).group(:status).count, height: "300px", colors: ["#007bff", "#28a745"] %>
  </div>
  <div class="col-md-6 chart-box">
    <%= column_chart Ticket.group_by_month(:created_at, format: "%b %Y").count, height: "300px", library: {title: {text: "Tickets by Month", x: -20}} %>
  </div>
</div>



</div>

app/views/pages/view.html.erb
<h1>hello view page</h1>
<%= link_to "More Insights", root_path , class: "btn btn-primary" %>
<%= link_to "Create Ticket", create_ticket_path , class: "btn btn-warning" %>