config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :contacts

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    get "view", to: "pages#view"
    resources :tickets, only: [:new, :create,:index, :show, :edit, :update]  do
      collection do
        get :show_ticket
      end
    end
    resources :messages, only: [:new, :create, :index] do
      collection do
        delete :clear
      end
    end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :contacts

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
    @company = Company.find(params[:id])
    @contacts = @company.contacts
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: "Company was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy!

    respond_to do |format|
      format.html { redirect_to companies_path, notice: "Company was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :address_section, :area, :city, :state, :country, :website, :phone, :territory)
    end
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">
  <p>
    <strong>Name:</strong>
    <%= company.name %>
  </p>

  <p>
    <strong>Address section:</strong>
    <%= company.address_section %>
  </p>

  <p>
    <strong>Area:</strong>
    <%= company.area %>
  </p>

  <p>
    <strong>City:</strong>
    <%= company.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= company.state %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= company.country %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= company.website %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= company.phone %>
  </p>

  <p>
    <strong>Territory:</strong>
    <%= company.territory %>
  </p>

</div>

app/views/companies/_company_card.html.erb
<div class="card mb-3" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= company.name %></h5>
    <p class="card-text"><%= company.territory %></p>
    <%= link_to 'Show this company', company_path(company), class: "btn btn-primary" %>
  </div>
</div>

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address_section %>
    <%= f.input :area %>
    <%= f.input :city %>
    <%= f.input :state %>
   <div class="field">
      <%= form.label :country %>
       <%= form.select :country, options_for_select(['India', 'USA', 'UK', 'Canada', 'Australia'], @company.country), prompt: "Select Country" %>
    </div>

    <%= f.input :website %>
    <%= f.input :phone %>
    <%= f.input :territory %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= form_with(model: @company) do |form| %>
  <%= render "form", form: form %>
<% end %>

<br>

<div>
  <%= link_to "Show this company", @company %> |
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-between align-items-center mb-5">
  <h1 class="mb-0">Companies</h1>
  <%= link_to "New company", new_company_path, class: "btn px-4", style: "background-color: #6ea8fe; border-radius: 18px; margin-right: 11%;" %>
</div>

<div class="company-cards-row">
  <% @companies.each do |company| %>
    <%= render partial: "company_card", locals: { company: company } %>
  <% end %>
</div>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= form_with(model: @company) do |form| %>
  <%= render "form", form: form %>
<% end %>

<br>

<div>
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @company %>

<div>
  <%= link_to "Edit this company", edit_company_path(@company) %> |
  <%= link_to "Back to companies", companies_path %>

  <%= link_to "Create Contact"%>
  <%= link_to "Create Contact", new_contact_path(company_id: @company.id), class: "btn btn-success" %>


  <%= button_to "Destroy this company", @company, method: :delete %>

  <h3>Contacts</h3>
<ul>
  <% @company.contacts.each do |contact| %>
    <li>
      <%= contact.contact_person %> - <%= contact.designation %> - <%= contact.phone %> - <%= contact.email %>
    </li>
  <% end %>
</ul>

</div>